default_target: rock_and_roll

.PHONY :
.SILENT: 

rock_and_roll: message
	$(MAKE) -sf $(Fi_CURRENT_DIR)/arch/Makefile.2 \
	Fi_CURRENT_DIR=$(Fi_CURRENT_DIR)/arch

	$(MAKE) -sf $(Fi_CURRENT_DIR)/stdk/Makefile.2 \
	Fi_CURRENT_DIR=$(Fi_CURRENT_DIR)/stdk

message: 
	echo -e "Building ENIGMA ($(Fi_VERSION))\n"