default_target: rock_and_roll

# The build configuration.

include buildconf

SRC_DIR := $(Fi_CURRENT_DIR)

SRC_FILES_ASM := $(wildcard $(SRC_DIR)/*.asm)
SRC_FILES_C   := $(wildcard $(SRC_DIR)/*.c)
OBJ_FILES_ASM := $(patsubst $(SRC_DIR)/%.asm, $(Bu_OBJ_DIR)/%.asm.obj, \
                 $(SRC_FILES_ASM))
OBJ_FILES_C   := $(patsubst $(SRC_DIR)/%.c, $(Bu_OBJ_DIR)/%.c.obj, \
                 $(SRC_FILES_C))

.PHONY :
.SILENT: 

rock_and_roll: message $(OBJ_FILES_ASM) $(OBJ_FILES_C)

# Build the ASM translations.

$(Bu_OBJ_DIR)/%.asm.obj: $(SRC_DIR)/%.asm
	$(Bu_ASM_BUILD_PRINT)
	$(Bu_ASM_BUILD)

# Build the C translations.

$(Bu_OBJ_DIR)/%.c.obj: $(SRC_DIR)/%.c
	$(Bu_C_BUILD_PRINT)
	$(Bu_C_BUILD)

message: 
	echo "Building 'stdk/i386/'"