default_target: rock_and_roll

# Local include directory.

LOCAL_INCLUDE := $(Fi_CURRENT_DIR)/include/

# Now build arch. specific modules.

.PHONY :
.SILENT: 

rock_and_roll: message
	$(MAKE) -sf $(Fi_CURRENT_DIR)/boot/Makefile.4 \
	Fi_CURRENT_DIR=$(Fi_CURRENT_DIR)/boot \
	Fi_LOCAL_INCLUDE=$(LOCAL_INCLUDE)

message: 
	echo "Building 'arch/i386/'"