default_target : rock_and_roll

# The parent config file. Will be filled by the upper-order Makefile.

Fi_PARENT_CONFIG := 

# The current directory.

Fi_CURRENT_DIR := .

# Now build arch. specific modules.

.PHONY  :
.SILENT : 

rock_and_roll : message
	$(MAKE) -sf $(Fi_CURRENT_DIR)/boot/Makefile.4 \
	Fi_CURRENT_DIR=$(Fi_CURRENT_DIR)/boot \
	Fi_PARENT_CONFIG=$(Fi_PARENT_CONFIG)

message : 
	echo "Building : arch/i386/"