default_target : rock_and_roll

include buildconf

SRC_DIR := $(Fi_CURRENT_DIR)

SRC_FILES_ASM := $(wildcard $(SRC_DIR)/*.asm)
OBJ_FILES_ASM := $(patsubst $(SRC_DIR)/%.asm, $(Bu_OBJ_DIR)/%.asm.obj, \
                 $(SRC_FILES_ASM))

rock_and_roll : message $(OBJ_FILES_ASM)

$(Bu_OBJ_DIR)/%.asm.obj : $(SRC_DIR)/%.asm
	$(Bu_ASM_BUILD_PRINT)
	$(Bu_ASM_BUILD)

message : 
	echo -e "\nBuilding 'arch/i386/boot/multiboot2/'"