default_target: rock_and_roll

# The build configuration and the root config file.

include buildconf
include config

SRC_DIR := $(Fi_CURRENT_DIR)

SRC_FILES_ASM := $(wildcard $(SRC_DIR)/*.asm)
SRC_FILES_C   := $(wildcard $(SRC_DIR)/*.c)
OBJ_FILES_ASM := $(patsubst $(SRC_DIR)/%.asm, $(Bu_OBJ_DIR)/%.asm.obj, \
                 $(SRC_FILES_ASM))
OBJ_FILES_C   := $(patsubst $(SRC_DIR)/%.c, $(Bu_OBJ_DIR)/%.c.obj, \
                 $(SRC_FILES_C))

.PHONY :
.SILENT: 

rock_and_roll: message $(OBJ_FILES_ASM) $(OBJ_FILES_C) config_specific_build

# Configuration specific builds.

config_specific_build: 
# Multiboot2 header.

ifeq ($(MULTIBOOT2_BOOT), yes) 
	$(MAKE) -sf $(Fi_CURRENT_DIR)/multiboot2/Makefile.5 \
	Fi_CURRENT_DIR=$(Fi_CURRENT_DIR)/multiboot2
endif

# Build the ASM translations.

$(Bu_OBJ_DIR)/%.asm.obj: $(SRC_DIR)/%.asm
	$(Bu_ASM_BUILD_PRINT)
	$(Bu_ASM_BUILD)

$(Bu_OBJ_DIR)/%.c.obj: $(SRC_DIR)/%.c
	$(Bu_C_BUILD_PRINT)
	$(Bu_C_BUILD)

message: 
	echo "Building 'arch/i386/boot/'"

# Include the dependencies.

-include $(patsubst $(Bu_OBJ_DIR)/%.c.obj, $(Bu_DEPS_DIR)/%.c.dep, $(OBJ_FILES_C))